# SearXNG settings

use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 2
  autocomplete: 'duckduckgo'
  formats:
    - html
    - json

server:
  # Is overwritten by ${SEARXNG_SECRET}
  secret_key: "ultrasecretkey"
  limiter: true
  image_proxy: true
  # public URL of the instance, to ensure correct inbound links. Is overwritten
  # by ${SEARXNG_URL}.
  # base_url: http://example.com/location

redis:
  # URL to connect redis database. Is overwritten by ${SEARXNG_REDIS_URL}.
  url: unix:///usr/local/searxng-redis/run/redis.sock?db=0

ui:
  static_use_hash: true

# preferences:
#   lock:
#     - autocomplete
#     - method

enabled_plugins:
  - 'Hash plugin'
  - 'Self Informations'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'
  # - 'Hostnames plugin'  # see 'hostnames' configuration below
  # - 'Open Access DOI rewrite'

# plugins:
#   - only_show_green_results

# hostnames:
#   replace:
#     '(.*\.)?youtube\.com$': 'invidious.example.com'
#     '(.*\.)?youtu\.be$': 'invidious.example.com'
#   remove:
#     - '(.*\.)?facebook.com$'
#   low_priority:
#     - '(.*\.)?google\.com$'
#   high_priority:
#     - '(.*\.)?wikipedia.org$'

engines:
  # General search engines with good privacy
  - name: duckduckgo
    disabled: false
    weight: 3
    timeout: 7.0
    shortcut: ddg

  - name: brave
    disabled: false
    weight: 3
    timeout: 7.0
    shortcut: brave

  - name: startpage
    disabled: false
    weight: 3
    timeout: 7.0
    shortcut: sp

  - name: searx
    disabled: false
    weight: 1
    timeout: 7.0
    shortcut: sx

  # Big search engines (good results but less privacy)
  - name: google
    disabled: false
    weight: 2
    timeout: 7.0
    shortcut: g

  - name: bing
    disabled: false
    weight: 1
    timeout: 7.0
    shortcut: b

  # Specialized search engines
  - name: wikipedia
    disabled: false
    weight: 2
    shortcut: wp

  - name: stackoverflow
    disabled: false
    shortcut: so

  - name: github
    disabled: false
    shortcut: gh

  - name: arxiv
    disabled: false
    shortcut: arx

  - name: semantic scholar
    disabled: false
    shortcut: ss

  # Images
  - name: google images
    disabled: false
    shortcut: gi

  - name: bing images
    disabled: false
    shortcut: bi

  # Videos
  - name: youtube
    disabled: false
    shortcut: yt

  # News
  - name: google news
    disabled: false
    shortcut: gn

  # Maps
  - name: openstreetmap
    disabled: false
    shortcut: osm

  # Torrents
  - name: piratebay
    disabled: false
    shortcut: tpb

  - name: nyaa
    disabled: false
    shortcut: nyaa

  # Science
  - name: pubmed
    disabled: false
    shortcut: pm

  # Shopping
  - name: amazon
    disabled: false
    shortcut: az

  # IT
  - name: npm
    disabled: false
    shortcut: npm

  - name: pypi
    disabled: false
    shortcut: pypi